//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Course_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accounting
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Accounting()
        {
            this.FoodProducts = new HashSet<FoodProducts>();
            this.Medicines = new HashSet<Medicines>();
            this.ShelterNeeds = new HashSet<ShelterNeeds>();
        }
    
        public int id { get; set; }
        public System.DateTime accounting_date { get; set; }
        public decimal salary { get; set; }
        public decimal utilities { get; set; }
        public decimal taxes { get; set; }
        public decimal medicine_expenses { get; set; }
        public decimal food_expenses { get; set; }
        public decimal shelter_needs_expenses { get; set; }
        public decimal other_expenses { get; set; }
        public decimal voluntary_contributions { get; set; }
        public Nullable<decimal> total { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FoodProducts> FoodProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Medicines> Medicines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShelterNeeds> ShelterNeeds { get; set; }
    }
}
