//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Course_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accounting
    {
        public int id { get; set; }
        public System.DateTime accounting_date { get; set; }
        public Nullable<decimal> salary { get; set; }
        public Nullable<decimal> utilities { get; set; }
        public Nullable<decimal> taxes { get; set; }
        public Nullable<decimal> medicine_expenses { get; set; }
        public Nullable<decimal> food_expenses { get; set; }
        public Nullable<decimal> other_expenses { get; set; }
        public Nullable<decimal> voluntary_contributions { get; set; }
        public Nullable<decimal> total { get; set; }
    }
}
