//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Course_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dogs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dogs()
        {
            this.Medicines = new HashSet<Medicines>();
            this.ParasiteTreatmentSchedule = new HashSet<ParasiteTreatmentSchedule>();
            this.PlannedEvents = new HashSet<PlannedEvents>();
            this.VaccinationSchedule = new HashSet<VaccinationSchedule>();
            this.WalkingSchedule = new HashSet<WalkingSchedule>();
        }
    
        public int id { get; set; }
        public string nickname { get; set; }
        public int age { get; set; }
        public string gender { get; set; }
        public string additional_information { get; set; }
        public byte[] image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Medicines> Medicines { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParasiteTreatmentSchedule> ParasiteTreatmentSchedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlannedEvents> PlannedEvents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VaccinationSchedule> VaccinationSchedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WalkingSchedule> WalkingSchedule { get; set; }
    }
}
