//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Course_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShelterEmployees
    {
        public int id { get; set; }
        public string FIO { get; set; }
        public string passport { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string place_of_registration { get; set; }
        public string actual_address { get; set; }
        public System.DateTime date_of_birth { get; set; }
        public string SNILS { get; set; }
        public string state_number_of_car { get; set; }
    }
}
